print("Inserte su nombre: ", end=' ')
name = input()
print("Escriba su apellido: ", end=' ')
lastname = input()
print("Ingrese su edad", end=' ')
age = input()

print("." * 10)
print(f"Su nombre completo es {name} {lastname}")
print(f"y su edad es de {age} años")
